CREATE TABLE tarifa (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	codigo_origem VARCHAR(3) NOT NULL,
	codigo_destino VARCHAR(3) NOT NULL,
	valor DOUBLE (7,2) NOT NULL
);

CREATE TABLE plano (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(3) NOT NULL,
	tempo VARCHAR(3) NOT NULL
);